// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DemoAPICrud
{
    public partial class Facture
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public string Objet { get; set; }
        public double? Montant { get; set; }
        public string Type { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
    }
}